project_name: mini_llm_2026

model:
  vocab_size: 50000
  max_seq_len: 512
  d_model: 768
  n_layers: 12
  n_heads: 12
  n_kv_heads: 4
  d_ff: 3072
  dropout: 0.0
  rotary_base: 10000
  rotary_scaling_factor: 1.0
  tie_embeddings: true
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2

training:
  seed: 42
  precision: bf16
  gradient_checkpointing: true
  use_compile: false #TODO false
  max_steps: 50000 #100000
  grad_accum_steps: 1 
  micro_batch_size: 18
  max_grad_norm: 1.0
  lr: 6.0e-4
  min_lr: 6.0e-5
  warmup_steps: 1000 #TODO 
  weight_decay: 0.1
  betas: [0.9, 0.95]
  save_every: 2000 #TODO 
  eval_every_steps: 2000 #TODO
  log_every: 20
  mtp_weight_1: 1.0
  mtp_weight_2: 0.5
  num_workers: 0
  pin_memory: true
  generation_use_chat: false

data:
  tokenizer_path: artifacts\qwentokenizer.json
  train_cache: artifacts/train_tokens.bin
  val_cache: artifacts/val_tokens.bin
  raw_train_paths:
    - data\base_openwebtext.jsonl
    #- data\base_tinystories.jsonl
  raw_val_paths:
    - data/val.jsonl
  val_split_ratio: 0.000002
  cache_dtype: uint32
  overwrite_cache: true
  chat_template:
    system: " "
    user_prefix: "<|user|>"
    assistant_prefix: "<|assistant|>"
    system_prefix: "<|system|>"

validation_prompts:
  - "In the wake of Trump's decision on The Paris Agreement, founder of Protect Our Winters Jeremy Jones..."
  - "As we start to look ahead to training camp, we're going to take a "
  - "Adrian Orr’s 23% salary increase has been decried by everyone from the PM down. But Orr is "
  - "For 35 years the Foreign Intelligence Surveillance Court has been the judicial equivalent of a "
  - "Yesterday, with time melting away, Landon Donovan raced into the Algerian penalty"
  - "Ban commends Nepali people on the adoption of the constitution, terming it a milestone in the peace "
  - "Tell me a joke about programmers."
  - "In private schools, as in private enterprise in general, poor performance drives funding away by "
  - "you see the doctor for a flu shot, you expect a jab in the arm "
  - "Write a friendly greeting message for a chatbot."

paths:
  output_dir: outputs/mini_llm_qwen_tokenizer_110m
  checkpoint_dir: outputs/mini_llm_qwen_tokenizer_110m/checkpoints
  tb_dir: outputs/mini_llm_qwen_tokenizer_110m/tensorboard
